### ISSUE TITLE
Auth

### ISSUE THREAD

**Issue by realjoshuau** [Team3256/app-old#2]
### Describe the feature you'd like to request

- Have a way to login to both the web app and the Expo app
- Set it up in such a way where users can have roles (i.e leads, vps, pit team, drive team) and associated permissions with said role (like MANAGE_ATTENDANCE, MANAGE_SCOUTING_ASSIGNMENTS, etcs)

**Comment by realjoshuau** [comment]
@ThatXliner Can you link your PR to this issue?

**Comment by ThatXliner** [comment]
Done
